log_level: info
use_sync_test: false
traces_dir: "traces/chat_firefox_h264"

path_characteristic_presets:
  standard:
    phases:
      - duration: 40s
        capacity: 1000000 # 1 Mbit/s
        max_burst: 160000 # 160 Kbit
      - duration: 40s
        capacity: 2500000 # 2.5 Mbit/s
        max_burst: 160000 # 160 Kbit
      - duration: 40s
        capacity: 600000 # 0.6 Mbit/s
        max_burst: 160000 # 160 Kbit
      - duration: 40s
        capacity: 1000000 # 1 Mbit/s
        max_burst: 160000 # 160 Kbit

  double:
    phases:
      - duration: 40s
        capacity: 2000000 # 2 Mbit/s
        max_burst: 160000 # 160 Kbit
      - duration: 40s
        capacity: 5000000 # 5 Mbit/s
        max_burst: 160000 # 160 Kbit
      - duration: 40s
        capacity: 1200000 # 1.2 Mbit/s
        max_burst: 160000 # 160 Kbit
      - duration: 40s
        capacity: 2000000 # 2 Mbit/s
        max_burst: 160000 # 160 Kbit

simulcast_configs_presets:
  standard:
    initial_quality: "360p"
    qualities:
      - name: "180p"
        bitrate: 225000
        trace_file: "chat_180p_400.txt"
        id: 2
      - name: "360p"
        bitrate: 591000
        trace_file: "chat_360p_1000.txt"
        id: 3
      - name: "720p"
        bitrate: 1753000
        trace_file: "chat_720p_2000.txt"
        id: 4

test_cases:
  - name: TestVnetRunnerABR/VariableAvailableCapacitySingleFlow
    flow_mode: single
    path_characteristic_preset: standard
    sender:
      mode: abr

  - name: TestVnetRunnerSimulcast/VariableAvailableCapacitySingleFlow
    flow_mode: single
    path_characteristic_preset: standard
    sender:
      mode: simulcast
      tracks:
        - name: "A"
          id: 1
          simulcast_preset: "standard"

  - name: TestVnetRunnerSimulcast/VariableAvailableCapacity3SimulcastTracks
    flow_mode: single
    path_characteristic_preset: double
    sender:
      mode: simulcast
      tracks:
        - name: "Track A"
          id: 1
          simulcast_preset: "standard"
        - name: "Track B"
          id: 2
          simulcast_preset: "standard"
        - name: "Track C"
          id: 3
          simulcast_preset: "standard"
