log_level: info
use_sync_test: true

test_cases:
  - name: TestVnetRunnerABR/VariableAvailableCapacitySingleFlow
    sender_mode: abr
    flow_mode: single
    path_characteristic:
      phases:
        - duration: 40s
          capacity: 1000000  # 1 Mbit/s
          max_burst: 160000  # 160 Kbit
        - duration: 20s
          capacity: 2500000  # 2.5 Mbit/s
          max_burst: 160000  # 160 Kbit
        - duration: 20s
          capacity: 600000   # 0.6 Mbit/s
          max_burst: 160000  # 160 Kbit
        - duration: 20s
          capacity: 1000000  # 1 Mbit/s
          max_burst: 160000  # 160 Kbit

  - name: TestVnetRunnerABR/VariableAvailableCapacityMultipleFlows
    sender_mode: abr
    flow_mode: multiple
    path_characteristic:
      phases:
        - duration: 25s
          capacity: 2000000  # 2 Mbit/s
          max_burst: 160000  # 160 Kbit
        - duration: 25s
          capacity: 1000000  # 1 Mbit/s
          max_burst: 160000  # 160 Kbit
        - duration: 25s
          capacity: 1750000  # 1.75 Mbit/s
          max_burst: 160000  # 160 Kbit
        - duration: 25s
          capacity: 500000   # 0.5 Mbit/s
          max_burst: 160000  # 160 Kbit
        - duration: 25s
          capacity: 1000000  # 1 Mbit/s
          max_burst: 160000  # 160 Kbit

  - name: TestVnetRunnerSimulcast/VariableAvailableCapacitySingleFlow
    sender_mode: simulcast
    flow_mode: single
    path_characteristic:
      phases:
        - duration: 40s
          capacity: 1000000  # 1 Mbit/s
          max_burst: 160000  # 160 Kbit
        - duration: 20s
          capacity: 2500000  # 2.5 Mbit/s
          max_burst: 160000  # 160 Kbit
        - duration: 20s
          capacity: 600000   # 0.6 Mbit/s
          max_burst: 160000  # 160 Kbit
        - duration: 20s
          capacity: 1000000  # 1 Mbit/s
          max_burst: 160000  # 160 Kbit

  - name: TestVnetRunnerSimulcast/VariableAvailableCapacityMultipleFlows
    sender_mode: simulcast
    flow_mode: multiple
    path_characteristic:
      phases:
        - duration: 25s
          capacity: 2000000  # 2 Mbit/s
          max_burst: 160000  # 160 Kbit
        - duration: 25s
          capacity: 1000000  # 1 Mbit/s
          max_burst: 160000  # 160 Kbit
        - duration: 25s
          capacity: 1750000  # 1.75 Mbit/s
          max_burst: 160000  # 160 Kbit
        - duration: 25s
          capacity: 500000   # 0.5 Mbit/s
          max_burst: 160000  # 160 Kbit
        - duration: 25s
          capacity: 1000000  # 1 Mbit/s
          max_burst: 160000  # 160 Kbit
